In [4]:
import fluxions as fl

# fl.jacobian
- Though implemented as a *function* rather than a *class*, `jacobian` was designed to maintain the Fluxion API

  1. To compute the Jacobian of `F` with respect to `v`, evaluated at value(s) given by `v_mapping`: 
   
   <pre>
   jacobian(F, v, v_mapping)
   </pre>
   
  2. `jacobian` will always return a numpy array

***

### Example 1: 
function from $\mathbb{R^1} \rightarrow \mathbb{R^1}$: same as derivative (and returns scalar)

$$
\begin{aligned}
F(y) &= ylog(y) \\ 
\Rightarrow J_F(y) &= log(y) + 1 \\
\Rightarrow J_F(1) &= 1
\end{aligned}
$$

In [15]:
y = fl.Var('y')
log_y = fl.log(y)
f = y*log_y

display(
    f.diff({'y':1})
)

# Jacobian of a scalar function from R^1 -> R^1
display(
    fl.jacobian(f, ['y'], {'y':1})
)

array([[1.]])

array([[1.]])

***

### Example 2: 
If F is a function from $\mathbb{R^m} \rightarrow \mathbb{R^n}$, then `jacobian` returns an m:n array if `v_mapping` contains scalar variable mappings

   
$$
\begin{aligned}
F(x,y) &= \begin{bmatrix} x^2 \\ x ln(y) \end{bmatrix} \\ \\
\Rightarrow J_F(x,y) &= \begin{bmatrix}
2x & x^2 \\
ln(y) & x/y
\end{bmatrix} \\ \\
\Rightarrow J_F(2,1) &= \begin{bmatrix}
4 & 0 \\ 
0 & 2
\end{bmatrix}
\end{aligned}
$$

In [8]:
x = fl.Var('x')

# Jacobian of a vector-valued function
fl.jacobian([x**2, x*log_y], ['x','y'], {'x':2, 'y':1})

array([[4., 0.],
       [0., 2.]])

***

### Example 3:
`jacobian` handles tensors: if variables `v` mapped to vectors of length T, then `jacobian` returns an **m : n : T** array

In [9]:
# Jacobian of a 3:2:10 function
J = fl.jacobian([x**2, x*log_y, x+y], ['x','y'], {'x':np.linspace(1,10,10), 'y':np.logspace(1,10,10)})
J.shape

(2, 3, 10)

---

## Behind the scenes:

- Blindly pass dict of variable bindings down the computation tree, and know an array of partials will be returned

In [14]:
F = [x*y*z, y**2]
f1 = x*y*z
f2 = y**2

seed = {'x':1, 'y':1, 'z':1}
v_mapping = {'x':1, 'y':2, 'z':3}

display(
    f1.diff(v_mapping, seed)
)
display(
    f2.diff(v_mapping, seed)
)

array([[6., 3., 2.]])

array([[0., 4., 0.]])